/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    BitcoinSignature: {
      address:
        "0x505af9414212829b7ffac10f3d486556f6297a94c7d98784105ad112bf40afd",
      abi: [
        {
          type: "impl",
          name: "BitcoinSignatureImpl",
          interface_name: "contracts::BitcoinSignature::IBitcoinSignature",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::Secp256Signature",
          members: [
            {
              name: "r",
              type: "core::integer::u256",
            },
            {
              name: "s",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::bitcoin::BitcoinPublicKey",
          members: [
            {
              name: "x",
              type: "core::integer::u256",
            },
            {
              name: "y",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::BitcoinSignature::IBitcoinSignature",
          items: [
            {
              type: "function",
              name: "verify_message",
              inputs: [
                {
                  name: "message",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "signature",
                  type: "contracts::bitcoin::Secp256Signature",
                },
                {
                  name: "public_key",
                  type: "contracts::bitcoin::BitcoinPublicKey",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "step1",
              inputs: [
                {
                  name: "message",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "sha256",
              inputs: [
                {
                  name: "message",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
          kind: "struct",
          members: [
            {
              name: "step1",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "step2",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::BitcoinSignature::BitcoinSignature::Event",
          kind: "enum",
          variants: [
            {
              name: "BitcoinMessageHashing",
              type: "contracts::BitcoinSignature::BitcoinSignature::BitcoinMessageHashing",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x733f5fcae7f9868aada9d3484044fb846011244c229fea5415fe3058af988c",
    },
  },
} as const;

export default deployedContracts;
